x-app-common:
  &app-common
  image: jobfit_ai:local
  volumes:
    - ".:/jobfit-ai-dir"
  env_file:
    - .env

services:
  app:
    << : *app-common
    container_name: jobfit_ai__app
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.local
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - jobfit_ai__network
    command: 'runserver.sh'

  db:
    << : *app-common
    image: postgres:17
    container_name: jobfit_ai__db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - jobfit_ai__network

  mongo:
    << : *app-common
    image: mongo:8.0
    container_name: jobfit_ai__mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - jobfit_ai__network

  mongo-express:
    << : *app-common
    image: mongo-express
    container_name: jobfit_ai__mongo_express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      mongo:
          condition: service_healthy
    networks:
      - jobfit_ai__network

volumes:
  mongo_data:
  postgres_data:
    driver: local

networks:
  jobfit_ai__network:
    driver: bridge
